include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: ignore
    prefer_const_constructors: ignore
    prefer_const_constructors_in_immutables: ignore
    avoid_print: ignore
    prefer_final_fields: ignore
    deprecated_member_use: ignore
    prefer_const_literals_to_create_immutables: ignore
    non_constant_identifier_names: ignore
    avoid_unnecessary_containers: ignore
    duplicate_ignore: ignore
    unused_element: ignore
    depend_on_referenced_packages: ignore
